# Generated by Django 2.0.9 on 2018-12-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comment',
            field=models.ForeignKey(on_delete=None, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
