# Generated by Django 2.0.9 on 2018-12-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181230_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('body', models.TextField(default=None, max_length=500, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=None, to='posts.Post')),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
