# Generated by Django 2.0.9 on 2018-12-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181230_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
